### PR TITLE
[WIP] switch to new xtraits

### PR DESCRIPTION
**Pull request by wolfv**
This has the potential to reduce compilation time, and binary size for our pre-compiled library :)

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@wolfv I have pushed forward a bit on my fork, although this gave me some ideas for something else. Let 's discuss more tomorrow.

**Comment by wolfv** [comment]
alright!

**Comment by SylvainCorlay** [comment]
Basically I did not know you could use `this` in the constructor, so we can simplify xproperty by completely removing the need for the offset.

**Comment by SylvainCorlay** [comment]
Closing as it was superseded by later PRs.

**Pull request closed without merging**
