### PR TITLE
Headers need not be listed in CMakeLists.txt

### PR DESCRIPTION
**Pull request by AntoinePrv**

### CODE REVIEW

**Comment by JohanMabille** [comment]
I think `you` need them, otherwise a change in the headers may not trigger a rebuild.

**Comment by AntoinePrv** [comment]
Just tested that, and it seems CMake is able to do the right thing, that is, check for changes in all headers in the directory.

It seems to work for headers outside the project too.

**Comment by JohanMabille** [comment]
Which version of cmake?

**Comment by AntoinePrv** [comment]
From conda-forge, I'm always getting an up-to-date CMake (3.25 today). Which version would you like me to try.

Note that if the only concern is about detecting header changes, this would only impact during development (not in releases).

**Comment by JohanMabille** [comment]
Can you rebase the PR? I think we should go this way for the whole stack to simplify the CMakeLists.txt. Also it seems the PUBLIC_HEADER property was initially specific to framework libraries on OSX, and works on other platforms for compatibility. Therefore we should not use this feature.

**Pull request merged**
